version: 2
jobs:
  build:
    docker:
      - image: node:8.15.0-stretch
    steps:
      - checkout
      - run: npm install
      - run:
          name: Print the Current Time
          command: date