version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub"
          command: |
            cp Dockerfile.production Dockerfile
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t heriot/learning-devops-demo1 .
              docker build -t heriot/learning-devops-demo1:${CIRCLE_SHA1} .
              docker push heriot/learning-devops-demo1                      
              docker push heriot/learning-devops-demo1:${CIRCLE_SHA1}
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              docker build -t heriot/learning-devops-demo1 .
              docker push heriot/learning-devops-demo1 
            else "This is ${CIRCLE_BRANCH}"
            fi
      - run:
          name: "Call to rancher to deploy"
          command: |
              docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
                --imageUuid 'docker:heriot/learning-devops-demo1:latest' \
                --batch_size 3 --start_first \
                --auto_complete --timeout 1200
      - run: echo Done
