workflows:
  version: 2
  build_test_ship_deploy:
    job:
      - build
      - test:
          requires:
            - build
      - ship:
          requires:
            - build
            - test
      - deploy:
          type:approval
          requires:
            - build
            - test
            - ship